# Generated by Django 4.2.2 on 2023-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='full_details',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='items',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lat_lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rid',
            field=models.IntegerField(unique=True),
        ),
    ]
